### ISSUE TITLE
판교 캠퍼스도 추가해주세요

### ISSUE THREAD

**Issue by ForeSummit** [kimhanjoon/sdsfoodcourtmenu#13]
판교 캠퍼스도 추가해주세요

**Comment by kimhanjoon** [comment]
판교도 추가해봤습니다~ 
@58aa2e86cc7384ba26ae9ff83e5c8ce0ee329c5f

**Comment by ForeSummit** [comment]
와우 감사합니다 ~~


오전까지 안 보여서 기대안하고 있었거든요 




네이버 메일 앱에서 보냈습니다.

-----Original Message-----
보낸사람: "Kim, Hanjoon" &lt;notifications@github.com&gt;
받는사람: "kimhanjoon/sdsfoodcourtmenu" &lt;sdsfoodcourtmenu@noreply.github.com&gt;
참조: "Jung-Jaemi" &lt;jaemy98@naver.com&gt;,"Author" &lt;author@noreply.github.com&gt;
날짜: 2017.02.06 오전 11:37:41
제목: Re: [kimhanjoon/sdsfoodcourtmenu] 판교 캠퍼스도 추가해주세요 (#13)



판교도 추가해봤습니다~

@58aa2e8

**Comment by ForeSummit** [comment]
혹시  판교 캠퍼스 :   오리지날  URL 정보  공유 가능할까요 ?

**Comment by kimhanjoon** [comment]
실망하시겠지만, 공지게시물 엑셀 수동입력입니다. 웰스토리에서 이런거 오픈API로 하면 좋을텐데 말이죠~

**Comment by ForeSummit** [comment]
에궁 . 이렇게 어렵게 작업하시는지 알았으면  부탁 안 드렸을텐데요. ㅠㅠ

판교 식단  게시하시는 분 통해서 알아보니
판교 식단 관련  URL이나 API가 없는 것 같습니다.

혹시  응용모바일  위원님이신가요 ?
